[package]
name = "rot-fixture"
version = "0.0.0"
edition = "2024"
build = "build/custom.rs"

[workspace]

[features]
default = ["prod_feature"]
prod_feature = []
testability = []
excluded = []
strong_dependency_feature = ["fixture-helper/marker"]
weak_dependency_feature = ["fixture-helper?/marker"]

[dependencies]
fixture-helper = { path = "../dependency", optional = true }

[lib]
test = false
bench = true

[[bin]]
name = "rot-fixture-bin"
path = "src/main.rs"
test = false
bench = false

[[test]]
name = "external"
path = "integration/check.rs"

[[example]]
name = "demo"
path = "demo/demo.rs"
test = true

[[bench]]
name = "speed"
path = "perf/bench.rs"
harness = false
